### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by patvdv** [hasherdk/s3-health#1]
Hi,

This is not really an issue nor complaint, more a warning for those who run into the same situation. 

I am using about a dozen S3 buckets on the [UpCloud](https://www.upcloud.com) provider which offers an S3-compatible service. There is about a half a million of documents in total in all of the buckets.

The _s3-health_ container runs with a CPU usage of 80%-90% continuously, which - I am guessing - is due to the amount of buckets and objects. Possibly it drops off after a while but I didn't notice any different behaviour even after a good 20 minutes of container run time.

I introduced CPU limits for the _s3-health_ container in my docker compose file:
```
  s3-health:
    image: ghcr.io/hasherdk/s3-health:latest
    container_name: s3-health
    deploy:
      resources:
        limits:
          cpus: '0.05'
        reservations:
          cpus: '0.03'
    environment:
      - S3_KEY=your_access_key
      - S3_SECRET=your_secret_key
      - S3_ENDPOINT=https://s3_endpoint_url
    restart: always
```
This keeps the CPU well within reasonable limits, it just takes a bit longer for the container to become fully online.

Additionally, I have set up an _Uptime-Kuma_ monitor on a particular S3 buckets with only about 20 documents. This helps in getting faster responses from the _s3-health_ API.

As always YMMV. Thanks for the nifty script!
